# Generated by Django 5.0.6 on 2024-06-11 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='Enter Product Name')),
                ('icon', models.ImageField(upload_to='ProductImage/', verbose_name='Select Product Icon')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Enter Product Price')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_product', to='product.game', verbose_name='Select Game')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
