# Generated by Django 5.0.6 on 2024-06-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_short_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='item_icon',
            field=models.ImageField(blank=True, null=True, upload_to='ProductImage/', verbose_name='Select Product Item Icon'),
        ),
    ]
