# Generated by Django 5.0.6 on 2024-06-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_slider_options_product_is_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Enter Payment Method Name')),
                ('logo', models.ImageField(upload_to='paymentmethod/')),
            ],
        ),
    ]
