# Generated by Django 5.0.6 on 2024-06-14 12:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_center', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='CompanyLogo/', verbose_name='Select Logo')),
                ('favicon', models.ImageField(upload_to='Favicon/', verbose_name='Select favicon')),
                ('meta_name', models.CharField(max_length=200)),
                ('meta_description', models.TextField()),
                ('meta_property', models.TextField()),
                ('description', models.TextField()),
                ('keyword', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
