# Generated by Django 5.0.6 on 2024-06-11 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_paymentmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=150, verbose_name='Game ID')),
                ('order_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('accept', 'Accept'), ('cancle', 'Cancle'), ('success', 'Success')], default='pending', max_length=50, null=True, verbose_name='Order Status')),
                ('totalPrice', models.FloatField(blank=True, null=True, verbose_name='Total Price')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_method', to='product.paymentmethod', verbose_name='Payment Method')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdetails', to='product.product', verbose_name='Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ordered_date', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
                ('product_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product_item', to='product.productitem')),
            ],
            options={
                'ordering': ('-ordered_date',),
            },
        ),
    ]
