# Generated by Django 5.0.6 on 2024-06-11 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0008_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product_item', to='product.productitem'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
