# Generated by Django 5.0.6 on 2024-09-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_product_item_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chatgpt_login_email',
            field=models.EmailField(blank=True, default='user@example.com', max_length=254, null=True, verbose_name='ChatGPT Login Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='chatgpt_login_password',
            field=models.CharField(blank=True, default='defaultpassword', max_length=128, null=True, verbose_name='ChatGPT Login Password'),
        ),
        migrations.AddField(
            model_name='order',
            name='password_optional',
            field=models.CharField(blank=True, default='optionalpassword', max_length=128, null=True, verbose_name='Password (Optional)'),
        ),
        migrations.AddField(
            model_name='order',
            name='udemy_account_email',
            field=models.EmailField(blank=True, default='user@udemy.com', max_length=254, null=True, verbose_name='Udemy Account Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='udemy_course_url',
            field=models.URLField(blank=True, default='http://example.com', null=True, verbose_name='Udemy Course URL'),
        ),
    ]
