# Generated by Django 5.0.6 on 2024-09-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_chatgpt_login_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Promo Code')),
                ('discount_percentage', models.FloatField(verbose_name='Discount Percentage')),
                ('max_uses', models.IntegerField(default=1, verbose_name='Maximum Uses')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_to', models.DateTimeField(verbose_name='Valid To')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
    ]
